/*
 * generated by Xtext 2.12.0
 */
package dk.sdu.ffu.pint


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PintRuntimeModule extends AbstractPintRuntimeModule {
}
