/*
 * generated by Xtext 2.12.0
 */
package dk.sdu.ffu.pint


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PintStandaloneSetup extends PintStandaloneSetupGenerated {

	def static void doSetup() {
		new PintStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
